"""

    Geral

"""

BASE_URL = "http://127.0.0.1:5000/api/v1"

HEADERS = {
            'Content-Type': 'application/json'
        }

"""
    
    Test Accounts
    
"""

TEST_ACCOUNT_1 = "teste@1.com"
TEST_ACCOUNT_1_PASSWORD = "teste@1.com"
TEST_ACCOUNT_2 = "teste@2.com"
TEST_ACCOUNT_2_PASSWORD = "teste@2.com"
TEST_ACCOUNT_3 = "teste@3.com"
TEST_ACCOUNT_3_PASSWORD = "teste@3.com"

" Name "

TEST_ACCOUNT_1_DEFAULT_NAME = "teste 1"
TEST_ACCOUNT_2_DEFAULT_NAME = "teste 2"
TEST_ACCOUNT_3_DEFAULT_NAME = "teste 3"

" Username "

TEST_ACCOUNT_1_DEFAULT_USERNAME = "teste_1"
TEST_ACCOUNT_2_DEFAULT_USERNAME = "teste_2"
TEST_ACCOUNT_3_DEFAULT_USERNAME = "teste_3"

" Birth Date "

TEST_ACCOUNT_1_DEFAULT_BIRTHDATE = "15/3/2000"
TEST_ACCOUNT_2_DEFAULT_BIRTHDATE = "15/3/2000"
TEST_ACCOUNT_ERROR_BIRTHDATE = "15/3/2020"

" Image "

TEST_ACCOUNT_1_DEFAULT_IMAGE_SOURCE = "teste 1"
TEST_ACCOUNT_2_DEFAULT_IMAGE_SOURCE = "teste 2"

" Activity Level "

TEST_ACCOUNT_1_DEFAULT_ACTIVITY_LEVEL = 1.2
TEST_ACCOUNT_2_DEFAULT_ACTIVITY_LEVEL = 1.2

" Height "

TEST_ACCOUNT_1_DEFAULT_HEIGHT = 180
TEST_ACCOUNT_2_DEFAULT_HEIGHT = 190

TEST_ACCOUNT_ERROR_HEIGHT_UNDER =80
TEST_ACCOUNT_ERROR_HEIGHT_OVER =400
TEST_ACCOUNT_ERROR_HEIGHT_FORMAT = 1.9

" Sex "

TEST_ACCOUNT_1_DEFAULT_SEX = "NA"
TEST_ACCOUNT_2_DEFAULT_SEX = "M"

" Weight "

TEST_ACCOUNT_1_DEFAULT_WEIGHT = 80.1
TEST_ACCOUNT_2_DEFAULT_WEIGHT = 85

TEST_ACCOUNT_ERROR_WEIGHT_UNDER =20
TEST_ACCOUNT_ERROR_WEIGHT_OVER =400

