FROM python:3.7-slim

# Install cron package
RUN apt-get update && \
    apt-get install -y cron && \
    apt-get clean

# Copy your script files to the container
COPY ./scripts /scripts

# Copy the cron schedule file to the container
COPY ./scripts/cron_schedule.txt /etc/cron.d/cron_schedule

# Give execution rights on the cron schedule file
RUN chmod 0644 /etc/cron.d/cron_schedule

# Apply the cron schedule
RUN crontab /etc/cron.d/cron_schedule

ENV CONTAINER_HOME=/var/www

ADD . $CONTAINER_HOME
WORKDIR $CONTAINER_HOME

RUN pip install -r $CONTAINER_HOME/requirements.txt

