version: '3.1'
services:
    db:
      image: mysql:5.7
      restart: always
      container_name: flask_db
      ports:
        - "3306:3306"
      expose:
        - "3306"
      environment:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user123
        - MYSQL_DATABASE=flask_api
        - MYSQL_ROOT_PASSWORD=12345678
      volumes:
        - flask_volume:/var/lib/mysql
      networks:
        - flask_network
    flask_app:
        container_name: flask_app
        restart: always
        build:
                context: .
                dockerfile: Dockerfile-Flask
        volumes:
          - ./scripts:/scripts
        env_file: .env
        depends_on:
                - db
        networks:
                flask_network:
                        aliases:
                                - flask-network
        command: bash -c 'flask create_db && flask create_super_user && gunicorn --bind 0.0.0.0:8000 --workers 2 "run:create_run()"'
    nginx:
        image: nginx
        container_name: flask_nginx
        restart: always
        volumes:
                - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
                - 80:80
        depends_on:
                - flask_app
        networks:
                - flask_network
volumes:
        flask_volume:
networks:
        flask_network:
