FROM amazonlinux

# Install cron package
RUN yum update -y && \
    yum install -y cronie && \
    yum clean all

FROM python:3.7-slim

ENV CONTAINER_HOME=/var/www

ADD . $CONTAINER_HOME
WORKDIR $CONTAINER_HOME

RUN pip install -r $CONTAINER_HOME/requirements.txt

