FROM amazonlinux

# Install cron package
RUN yum update -y && \
    yum install -y cronie && \
    yum clean all

# Copy your script files to the container
COPY ./scripts /scripts

# Copy the cron schedule file to the container
COPY ./cron_schedule.txt /etc/cron.d/cron_schedule

# Give execution rights on the cron schedule file
RUN chmod 0644 /etc/cron.d/cron_schedule

# Apply the cron schedule
RUN crontab /etc/cron.d/cron_schedule

# Start the cron service
CMD ["cron", "-f"]