[default]
SQLALCHEMY_TRACK_MODIFICATIONS = "False"
SWAGGER_BASEPATH = "/api/v1/"

[development]
# When you switch to debug mode, the db name becomes localhost and port 3307.
DEBUG = "True"
DATABASE_HOST = "localhost:3306"
DATABASE_USER = "root"
DATABASE_PASSWORD = ""

[production]
# When in production, mostly in the docker, it keeps running this configuration
DEBUG = "False"
DATABASE_HOST = "flask_db"
DATABASE_USER = "root"
DATABASE_PASSWORD = "12345678"


